print("-----文字列を大文字→小文字、小文字→大文字の変換を行う-----")
print('\n', end='')
print("1.lower（全ての文字を小文字に変換する）")
print("DEVIL MAY CRY".lower())
print('\n', end='')
print("2.upper（全ての文字を大文字に変換する）")
print("biohazard revelations".upper())
print('\n', end='')
print("3.capitalize（最初の文字を大文字に変換、他は小文字にと区別して変換する）")
print("final fantasy".capitalize())
print("final".capitalize(), "fantasy".capitalize())
print('\n', end='')
print("4.title（単語毎に最初の文字を大文字に変換、他は小文字にと区別して変換する）")
print("MY FAVORITE GAMES".title())
print("my favorite games".title())
print('\n', end='')
print("5.swapcase（大文字を小文字に、小文字を大文字に変換する）")
print("Pazzle & Doragons".swapcase())
print("pazzle & doragons".swapcase())
print("PAZZLE & DORAGONS".swapcase())
