print("-----文字列の中に含まれる文字が大文字か小文字かを判定するのに使用できるメソッド-----")
print('\n', end='')
print("1.islower（すべての文字が小文字かどうかを判定するメソッド）")
print("❶全ての文字列が大文字/小文字の区別ができる文字列である場合 = 文字列中の全てが小文字の場合に「真」を返す")
print("baiohazard".islower()) #全て小文字
print("Baiohazard".islower()) #大文字を含む文字列
print('\n', end='')
print("❷数値や日本語などの大文字/小文字の区別ができない文字を含む場合 = 区別できない文字列は無視される(Tureとなる)")
print("baiohazard7".islower())
print("baiohazard発売開始!!".islower())
print('\n', end='')
print("❸全ての文字列が数値や日本語などの大文字/小文字の区別ができない文字列の場合 = 区別ができないとみなされる(falseとなる)")
print("2020/06/06".islower())
print("東京都足立区青井5丁目".islower())
print('\n', end='')
print('\n', end='')
print("2.islower（すべての文字が大文字かどうかを判定するメソッド）")
print("❶全ての文字列が大文字/小文字の区別ができる文字列である場合 = 文字列中の全てが大文字の場合に「真」を返す")
print("BAIOHAZARD".isupper()) #全て大文字
print("Baiohazard".isupper()) #小文字を含む文字列
print("❷全ての文字列が数値や日本語などの大文字/小文字の区別ができない文字列の場合 = 区別ができないとみなされる(falseとなる)")
print("2020/06/06".isupper())
print("東京都足立区青井5丁目".isupper())
print('\n', end='')
print('\n', end='')
print("3.istitle（文字列に含まれる単語毎に最初の文字が大文字で他は小文字かどうかを判定する）")
print("❶全ての文字列が大文字/小文字の区別ができる文字列である場合 = 単語の最初の文字が大文字、それ以外が小文字の場合に「真」を返す")
print("Rockman Exe".istitle())
print("ROCKMAN Exe".istitle())
print('\n', end='')
print('\n', end='')
print("❷数値や日本語などの大文字/小文字の区別ができない文字列を含む場合 = 小文字の前が大文字であれば「真」、それ以外の文字であれば「偽」を返す")
print("Rockman 2Exe".istitle())
print("Rockman Exe2".istitle())
print("Rockman E2xe".istitle())
print('\n', end='')
print('\n', end='')
print("❸全ての文字列が数値や日本語などの大文字/小文字の区別ができない文字列の場合 = 区別ができないとみなされる(falseとなる)")
print("2020/12/31".istitle())
print("山形県酒田市豊里字大割".islower())
