print("-----文字列の中に含まれる文字が英字を表す文字かどうかを判定する際に使用するメソッド-----")
print('\n', end='')
print("1.isascii（すべての文字がASCIIの場合、または空文字の場合は「真」とする）")
print("Japan".isascii())
print("19920809".isascii())
print("大阪府".isascii())
print("".isascii())
